{
 "title": "Axon Metrics Example Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BookSeatCommand counters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(commandBus_BookSeatCommand_failureCounter[30s])",
     "legendFormat": "BookSeatCommand_failureCounter"
    },
    {
     "expr": "irate(commandBus_BookSeatCommand_successCounter[30s])",
     "legendFormat": "BookSeatCommand_successCounter"
    },
    {
     "expr": "irate(commandBus_BookSeatCommand_ingestedCounter[30s])",
     "legendFormat": "BookSeatCommand_ingestedCounter"
    }
   ]
  },
  {
   "title": "Event listeners capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "eu_luminis_ams_axonmetrics_eventlistener_quick_SeatBookedEvent_1m_capacity",
     "legendFormat": "QuickEventListener_SeatBookedEvent"
    },
    {
     "expr": "eu_luminis_ams_axonmetrics_eventlistener_slow_SeatBookedEvent_1m_capacity",
     "legendFormat": "SlowEventListener_SeatBookedEvent"
    },
    {
     "expr": "eu_luminis_ams_axonmetrics_eventlistener_quick_FlightPlannedEvent_1m_capacity",
     "legendFormat": "QuickEventListener_FlightPlannedEvent"
    },
    {
     "expr": "eu_luminis_ams_axonmetrics_eventlistener_slow_FlightPlannedEvent_1m_capacity",
     "legendFormat": "SlowEventListener_FlightPlannedEvent"
    }
   ]
  },
  {
   "title": "Event listener process time 0.5 quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "eu_luminis_ams_axonmetrics_eventlistener_quick_FlightPlannedEvent_allTimer{quantile=\"0.5\"}",
     "legendFormat": "QuickEventListener_FlightPlannedEvent"
    },
    {
     "expr": "eu_luminis_ams_axonmetrics_eventlistener_slow_FlightPlannedEvent_allTimer{quantile=\"0.5\"}",
     "legendFormat": "SlowEventListener_FlightPlannedEvent"
    },
    {
     "expr": "eu_luminis_ams_axonmetrics_eventlistener_slow_SeatBookedEvent_allTimer{quantile=\"0.5\"}",
     "legendFormat": "SlowEventListener_SeatBookedEvent"
    },
    {
     "expr": "eu_luminis_ams_axonmetrics_eventlistener_quick_SeatBookedEvent_allTimer{quantile=\"0.5\"}",
     "legendFormat": "QuickEventListener_SeatBookedEvent"
    }
   ]
  }
 ]
}