version: '2.1'
services:

  prometheus:
    image: prom/prometheus:latest
    container_name: axon-metrics-example_prometheus
    depends_on:
      - axon-app
    ports:
      - 9090:9090
    volumes:
      - .:/etc/prometheus/

  axon-app:
    image: luminis-ams/axon-metrics-prometheus:0.0.1-SNAPSHOT
    container_name: axon-metrics-example_axon-app
    depends_on:
      axon-server:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - axon.axonserver.servers=axon-server

  grafana:
    image: grafana/grafana
    container_name: axon-metrics-example_grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000

  axon-server:
    image: axoniq/axonserver
    container_name: axon-metrics-example_axonserver
    healthcheck:
      test: "curl -f 'http://localhost:8024/actuator/health'"
    ports:
      - 8024:8024
      - 8124:8124

