version: '2.1'
services:

  prometheus:
    image: prom/prometheus:latest
    container_name: axon-metrics-example_prometheus_local
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana
    container_name: axon-metrics-example_grafana_local
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false

  axon-server:
    image: axoniq/axonserver
    container_name: axon-metrics-example_axonserver_local
    healthcheck:
      test: "curl -f 'http://localhost:8024/actuator/health'"
    ports:
      - 8024:8024
      - 8124:8124

